# Generated by Django 4.2.16 on 2024-09-10 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_temperature_level', models.FloatField()),
                ('lowest_temperature_level', models.FloatField()),
                ('highest_humidity_level', models.FloatField()),
                ('lowest_humidity_level', models.FloatField()),
                ('highest_ammonia_level', models.FloatField()),
                ('lowest_ammonia_level', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold_data', to='devicedata.devicedata')),
            ],
        ),
        migrations.CreateModel(
            name='ClimateControlData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heater', models.BooleanField(default=False)),
                ('cooling_fan', models.BooleanField(default=False)),
                ('humidifier', models.BooleanField(default=False)),
                ('exhaust_fan', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_control_data', to='devicedata.devicedata')),
            ],
        ),
    ]
